import { createVendor } from "@/app/admin/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, Td, Th } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { prisma } from "@/lib/prisma";

export default async function VendorsPage() { const vendors = await prisma.vendor.findMany({ include: { equipmentItems: true, prices: true }, orderBy: { name: "asc" } }); return <div className="space-y-6"><div><h1 className="text-3xl font-black text-[#071426]">Vendor database</h1><p className="mt-1 text-[#697386]">Altara-owned supplier records used before equipment purchase after client payment.</p></div><Card><CardHeader><CardTitle>Add vendor</CardTitle></CardHeader><CardContent><form action={createVendor} className="grid gap-3 md:grid-cols-3"><Input name="name" placeholder="Vendor name" required /><Input name="contactName" placeholder="Contact name" /><Input name="phone" placeholder="Phone" /><Input name="email" placeholder="Email" /><Input name="location" placeholder="Location" /><Input name="trustScore" type="number" min="0" max="100" defaultValue="50" /><Textarea name="deliveryNotes" placeholder="Delivery notes" /><Textarea name="paymentTerms" placeholder="Payment terms" /><Button type="submit">Add vendor</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Vendor records</CardTitle></CardHeader><CardContent><Table><thead><tr><Th>Name</Th><Th>Contact</Th><Th>Trust</Th><Th>Records</Th><Th>Notes</Th></tr></thead><tbody>{vendors.map((vendor) => <tr key={vendor.id}><Td className="font-bold">{vendor.name}<div className="text-xs text-[#697386]">{vendor.location}</div></Td><Td>{vendor.contactName}<div className="text-xs">{vendor.phone}<br />{vendor.email}</div></Td><Td>{vendor.trustScore}/100</Td><Td>{vendor.equipmentItems.length} equipment<br />{vendor.prices.length} prices</Td><Td className="max-w-md text-sm">{vendor.deliveryNotes}<br />{vendor.paymentTerms}</Td></tr>)}</tbody></Table></CardContent></Card></div>; }
